# Generated by Django 5.1.7 on 2025-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
